name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
compatibility_date = "2022-11-11"

d1_databases = [
  { binding = "DB", database_id = "<ignored>", database_name = "my_db" }
]

[site]
  bucket = "./public"

[build]
  command = "yarn build"
